const express = require("express");
const router = express.Router();
router.use('/access', require('./access.route'));
router.use('/products', require('./products.route'));
router.use('/', require('./public.route'));
router.use('/categories', require('./categories.route'));
router.use('/cart', require('./cart.route'));
router.use('/order', require('./order.route'));
router.use('/invoice', require('./invoice.route'));
router.use('/payment', require('./payment.route'));
router.use('/dashboard', require('./dashboard.route'));
module.exports = router;